const s = /* @__PURE__ */ location.pathname.split("/").slice(0, -1).join("/"), u = [
  s + "/_app/immutable/entry/app.cb50b7b2.js",
  s + "/_app/immutable/chunks/0.9e63d736.js",
  s + "/_app/immutable/chunks/1.5d2fffc5.js",
  s + "/_app/immutable/chunks/10.9c304c1d.js",
  s + "/_app/immutable/chunks/2.6d34dfb9.js",
  s + "/_app/immutable/chunks/3.518d61ed.js",
  s + "/_app/immutable/chunks/4.3e4814ab.js",
  s + "/_app/immutable/chunks/5.e0f413d3.js",
  s + "/_app/immutable/chunks/6.316f940e.js",
  s + "/_app/immutable/chunks/7.623c2dc2.js",
  s + "/_app/immutable/chunks/8.219c8078.js",
  s + "/_app/immutable/chunks/9.3f761cd6.js",
  s + "/_app/immutable/assets/SlottedTranslatableKey.2331979f.css",
  s + "/_app/immutable/chunks/DescribeAny.2787f5a4.js",
  s + "/_app/immutable/chunks/MetaTags.1177d526.js",
  s + "/_app/immutable/chunks/SlottedTranslatableKey.d14ed7d0.js",
  s + "/_app/immutable/chunks/_docs_all.935a8bd2.js",
  s + "/_app/immutable/chunks/_layout.20f8d1e9.js",
  s + "/_app/immutable/chunks/_layout.acc824bf.js",
  s + "/_app/immutable/chunks/_layout.ed5c238c.js",
  s + "/_app/immutable/chunks/_page.625d00c9.js",
  s + "/_app/immutable/chunks/_page.a8fa445c.js",
  s + "/_app/immutable/chunks/_page.e7aa1d55.js",
  s + "/_app/immutable/chunks/_page.e96476b2.js",
  s + "/_app/immutable/chunks/control.e7f5239e.js",
  s + "/_app/immutable/chunks/index.2defaa64.js",
  s + "/_app/immutable/chunks/index.89ff297d.js",
  s + "/_app/immutable/chunks/index.efdf84df.js",
  s + "/_app/immutable/chunks/landmark.b7ef530e.js",
  s + "/_app/immutable/chunks/loading.a7424ab9.js",
  s + "/_app/immutable/chunks/paths.f59edf16.js",
  s + "/_app/immutable/chunks/preload-helper.41c905a7.js",
  s + "/_app/immutable/chunks/singletons.bea7bd7d.js",
  s + "/_app/immutable/chunks/statistics.a5ef6ed5.js",
  s + "/_app/immutable/assets/statistics.4317ff0a.css",
  s + "/_app/immutable/assets/class.9795478b.webp",
  s + "/_app/immutable/assets/method.e780cc87.webp",
  s + "/_app/immutable/assets/destroy_stage_0.f499533e.png",
  s + "/_app/immutable/assets/destroy_stage_1.0de13fe3.png",
  s + "/_app/immutable/assets/destroy_stage_2.3dad4672.png",
  s + "/_app/immutable/assets/destroy_stage_3.47e37d00.png",
  s + "/_app/immutable/assets/destroy_stage_4.27806171.png",
  s + "/_app/immutable/assets/destroy_stage_5.a1594b01.png",
  s + "/_app/immutable/assets/destroy_stage_6.6f3ce9bb.png",
  s + "/_app/immutable/assets/destroy_stage_7.d3f13380.png",
  s + "/_app/immutable/assets/destroy_stage_8.0812dac1.png",
  s + "/_app/immutable/assets/destroy_stage_9.1a04b108.png",
  s + "/_app/immutable/assets/stone1.e94a295a.ogg",
  s + "/_app/immutable/assets/stone2.2cfbf878.ogg",
  s + "/_app/immutable/assets/stone3.c5d71e8d.ogg",
  s + "/_app/immutable/assets/stone4.95820d0b.ogg",
  s + "/_app/immutable/assets/stone5.67b1e504.ogg",
  s + "/_app/immutable/assets/stone6.2b65e1bd.ogg",
  s + "/_app/immutable/assets/stone1.97f2a8a7.ogg",
  s + "/_app/immutable/assets/stone2.98a5c319.ogg",
  s + "/_app/immutable/assets/stone3.19273f0e.ogg",
  s + "/_app/immutable/assets/stone4.b164e732.ogg",
  s + "/_app/immutable/assets/unlit_star.44b7d610.svg",
  s + "/_app/immutable/assets/star.150d3691.svg",
  s + "/_app/immutable/assets/field.8fb526b4.webp",
  s + "/_app/immutable/chunks/stores.e09e708b.js",
  s + "/_app/immutable/chunks/_docs_v-pre-5.837f3a70.js",
  s + "/_app/immutable/chunks/_docs_v-pre-5_en_uwu.254d77d2.js",
  s + "/_app/immutable/chunks/_docs_v-pre-6.c5c9ad42.js",
  s + "/_app/immutable/chunks/_docs_v-pre-6_en_uwu.16f2d150.js",
  s + "/_app/immutable/chunks/_docs_v-rc-1.4f837852.js",
  s + "/_app/immutable/chunks/_docs_v-rc-10.a2c1c3f9.js",
  s + "/_app/immutable/chunks/_docs_v-rc-10_en_uwu.810dc442.js",
  s + "/_app/immutable/chunks/_docs_v-rc-10_ru_ru.a68e3cb7.js",
  s + "/_app/immutable/chunks/_docs_v-rc-11.d6bc8901.js",
  s + "/_app/immutable/chunks/_docs_v-rc-11_en_uwu.c1a6db5c.js",
  s + "/_app/immutable/chunks/_docs_v-rc-11_ru_ru.a68e3cb7.js",
  s + "/_app/immutable/chunks/_docs_v-rc-12.09ce1d9d.js",
  s + "/_app/immutable/chunks/_docs_v-rc-12_en_uwu.428395a0.js",
  s + "/_app/immutable/chunks/_docs_v-rc-13.1acd5718.js",
  s + "/_app/immutable/chunks/_docs_v-rc-13_en_uwu.488e93cc.js",
  s + "/_app/immutable/chunks/_docs_v-rc-14.4fc6b209.js",
  s + "/_app/immutable/chunks/_docs_v-rc-14_en_uwu.342895a7.js",
  s + "/_app/immutable/chunks/_docs_v-rc-1_en_uwu.3f8427b8.js",
  s + "/_app/immutable/chunks/_docs_v-rc-1_ru_ru.a68e3cb7.js",
  s + "/_app/immutable/chunks/_docs_v-rc-2.f8549205.js",
  s + "/_app/immutable/chunks/_docs_v-rc-2_en_uwu.22a1f060.js",
  s + "/_app/immutable/chunks/_docs_v-rc-2_ru_ru.a68e3cb7.js",
  s + "/_app/immutable/chunks/_docs_v-rc-3.0a246ef3.js",
  s + "/_app/immutable/chunks/_docs_v-rc-3_en_uwu.d283fe95.js",
  s + "/_app/immutable/chunks/_docs_v-rc-3_ru_ru.a68e3cb7.js",
  s + "/_app/immutable/chunks/_docs_v-rc-4.49eb4a12.js",
  s + "/_app/immutable/chunks/_docs_v-rc-4_en_uwu.cbf3234c.js",
  s + "/_app/immutable/chunks/_docs_v-rc-4_ru_ru.a68e3cb7.js",
  s + "/_app/immutable/chunks/_docs_v-rc-5.c1f22dcc.js",
  s + "/_app/immutable/chunks/_docs_v-rc-5_en_uwu.7983e190.js",
  s + "/_app/immutable/chunks/_docs_v-rc-5_ru_ru.a68e3cb7.js",
  s + "/_app/immutable/chunks/_docs_v-rc-6.dcb45574.js",
  s + "/_app/immutable/chunks/_docs_v-rc-6_en_uwu.3fae3870.js",
  s + "/_app/immutable/chunks/_docs_v-rc-6_ru_ru.a68e3cb7.js",
  s + "/_app/immutable/chunks/_docs_v-rc-7.dab8bfbc.js",
  s + "/_app/immutable/chunks/_docs_v-rc-7_en_uwu.532e4151.js",
  s + "/_app/immutable/chunks/_docs_v-rc-7_ru_ru.a68e3cb7.js",
  s + "/_app/immutable/chunks/_docs_v-rc-8.4242b87e.js",
  s + "/_app/immutable/chunks/_docs_v-rc-8_en_uwu.5fed128f.js",
  s + "/_app/immutable/chunks/_docs_v-rc-8_ru_ru.a68e3cb7.js",
  s + "/_app/immutable/chunks/_docs_v-rc-9.d98cf3cd.js",
  s + "/_app/immutable/chunks/_docs_v-rc-9_en_uwu.ca8acb93.js",
  s + "/_app/immutable/chunks/_docs_v-rc-9_ru_ru.a68e3cb7.js",
  s + "/_app/immutable/entry/start.437736e0.js",
  s + "/_app/immutable/entry/error.svelte.f7fa29c9.js",
  s + "/_app/immutable/chunks/gravity.6d18d3f6.js",
  s + "/_app/immutable/chunks/pt_pt.cfc632b1.js",
  s + "/_app/immutable/assets/dirt.fb045025.png",
  s + "/_app/immutable/assets/grass_block.dedaa017.png",
  s + "/_app/immutable/assets/sign.c804ceb9.png",
  s + "/_app/immutable/assets/stone.0096954e.png",
  s + "/_app/immutable/assets/sun.d66e4fcc.png",
  s + "/_app/immutable/assets/cheese.9bdf176f.png",
  s + "/_app/immutable/assets/eh.6b23cd84.png",
  s + "/_app/immutable/assets/ok.56d3dd37.png",
  s + "/_app/immutable/assets/_layout.791fc342.css",
  s + "/_app/immutable/entry/_layout.svelte.d709ca38.js",
  s + "/_app/immutable/entry/_layout.ts.84f7d787.js",
  s + "/_app/immutable/assets/_page.b186cf5c.css",
  s + "/_app/immutable/entry/_page.svelte.fd8927b1.js",
  s + "/_app/immutable/entry/_version_-layout.svelte.50d8c737.js",
  s + "/_app/immutable/entry/_version_-layout.ts.186f439d.js",
  s + "/_app/immutable/entry/_version_-page.svelte.b72466e0.js",
  s + "/_app/immutable/entry/_version_-page.ts.1fa92697.js",
  s + "/_app/immutable/entry/_version_-_location_-page.svelte.3e60784d.js",
  s + "/_app/immutable/entry/_version_-_location_-page.ts.cd0719d0.js",
  s + "/_app/immutable/assets/_page.7408eda2.css",
  s + "/_app/immutable/entry/_version_-all-page.svelte.89dcce00.js",
  s + "/_app/immutable/entry/_version_-all-page.ts.3eac1f9a.js",
  s + "/_app/immutable/entry/_version_-fav-page.svelte.fc84592b.js",
  s + "/_app/immutable/entry/_version_-search-page.svelte.210c3342.js",
  s + "/_app/immutable/entry/_version_-search-page.ts.897bb2d1.js",
  s + "/_app/immutable/assets/_layout.88f12fff.css",
  s + "/_app/immutable/entry/etc-layout.svelte.9f036296.js",
  s + "/_app/immutable/entry/etc-layout.ts.ef9dea09.js",
  s + "/_app/immutable/assets/_page.32459e00.css",
  s + "/_app/immutable/entry/etc-what_are_pings-page.svx.072be371.js"
], m = [
  s + "/favicon.png",
  s + "/manifest.json"
], l = "1681559703794", _ = self, p = `A;static-cache-${l}`, c = u.concat(m);
console.log(c);
_.addEventListener("install", (a) => {
  console.log("[ServiceWorker] Install"), a.waitUntil(
    caches.open(p).then((e) => (console.log("[ServiceWorker] Pre-caching offline page"), e.addAll(c).then(() => {
      _.skipWaiting();
    })))
  );
});
_.addEventListener("activate", (a) => {
  console.log("[ServiceWorker] Activate"), console.log(a), a.waitUntil(
    caches.keys().then(
      async (e) => Promise.all(
        e.map((t) => {
          if (t !== p)
            return console.log("[ServiceWorker] Removing old cache", t), caches.delete(t);
        })
      )
    )
  ), _.clients.claim();
});
self.addEventListener("fetch", (a) => {
  console.log("[ServiceWorker] Fetch", a.request.url), a.respondWith(
    fetch(a.request).catch(() => caches.open(p).then((e) => (console.log(a.request), e.match(a.request.url))))
  );
});
