const a = /* @__PURE__ */ location.pathname.split("/").slice(0, -1).join("/"), u = [
  a + "/_app/immutable/entry/app.5a5bf8e9.js",
  a + "/_app/immutable/chunks/0.2fa17d68.js",
  a + "/_app/immutable/chunks/1.75981343.js",
  a + "/_app/immutable/chunks/10.f941c8cb.js",
  a + "/_app/immutable/chunks/2.6443d20f.js",
  a + "/_app/immutable/chunks/3.518d61ed.js",
  a + "/_app/immutable/chunks/4.1567e838.js",
  a + "/_app/immutable/chunks/5.e0f413d3.js",
  a + "/_app/immutable/chunks/6.3176c935.js",
  a + "/_app/immutable/chunks/7.e6323439.js",
  a + "/_app/immutable/chunks/8.c5681400.js",
  a + "/_app/immutable/chunks/9.a8e786ab.js",
  a + "/_app/immutable/assets/SlottedTranslatableKey.2331979f.css",
  a + "/_app/immutable/chunks/DescribeAny.b0b9385e.js",
  a + "/_app/immutable/chunks/MetaTags.1177d526.js",
  a + "/_app/immutable/chunks/SlottedTranslatableKey.d14ed7d0.js",
  a + "/_app/immutable/chunks/_docs_all.39739938.js",
  a + "/_app/immutable/chunks/_layout.321cf2de.js",
  a + "/_app/immutable/chunks/_layout.82e725ad.js",
  a + "/_app/immutable/chunks/_layout.ed5c238c.js",
  a + "/_app/immutable/chunks/_page.3add10ad.js",
  a + "/_app/immutable/chunks/_page.625d00c9.js",
  a + "/_app/immutable/chunks/_page.c81fc520.js",
  a + "/_app/immutable/chunks/_page.e7aa1d55.js",
  a + "/_app/immutable/chunks/control.e7f5239e.js",
  a + "/_app/immutable/chunks/index.2defaa64.js",
  a + "/_app/immutable/chunks/index.89ff297d.js",
  a + "/_app/immutable/chunks/index.efdf84df.js",
  a + "/_app/immutable/chunks/landmark.b7ef530e.js",
  a + "/_app/immutable/chunks/loading.a7424ab9.js",
  a + "/_app/immutable/chunks/paths.0afb57c2.js",
  a + "/_app/immutable/chunks/preload-helper.41c905a7.js",
  a + "/_app/immutable/chunks/singletons.53d4f5d9.js",
  a + "/_app/immutable/chunks/statistics.d0eef2bf.js",
  a + "/_app/immutable/assets/statistics.d2ad473c.css",
  a + "/_app/immutable/assets/class.9795478b.webp",
  a + "/_app/immutable/assets/method.e780cc87.webp",
  a + "/_app/immutable/assets/destroy_stage_0.f499533e.png",
  a + "/_app/immutable/assets/destroy_stage_1.0de13fe3.png",
  a + "/_app/immutable/assets/destroy_stage_2.3dad4672.png",
  a + "/_app/immutable/assets/destroy_stage_3.47e37d00.png",
  a + "/_app/immutable/assets/destroy_stage_4.27806171.png",
  a + "/_app/immutable/assets/destroy_stage_5.a1594b01.png",
  a + "/_app/immutable/assets/destroy_stage_6.6f3ce9bb.png",
  a + "/_app/immutable/assets/destroy_stage_7.d3f13380.png",
  a + "/_app/immutable/assets/destroy_stage_8.0812dac1.png",
  a + "/_app/immutable/assets/destroy_stage_9.1a04b108.png",
  a + "/_app/immutable/assets/stone1.e94a295a.ogg",
  a + "/_app/immutable/assets/stone2.2cfbf878.ogg",
  a + "/_app/immutable/assets/stone3.c5d71e8d.ogg",
  a + "/_app/immutable/assets/stone4.95820d0b.ogg",
  a + "/_app/immutable/assets/stone5.67b1e504.ogg",
  a + "/_app/immutable/assets/stone6.2b65e1bd.ogg",
  a + "/_app/immutable/assets/stone1.97f2a8a7.ogg",
  a + "/_app/immutable/assets/stone2.98a5c319.ogg",
  a + "/_app/immutable/assets/stone3.19273f0e.ogg",
  a + "/_app/immutable/assets/stone4.b164e732.ogg",
  a + "/_app/immutable/assets/unlit_star.44b7d610.svg",
  a + "/_app/immutable/assets/star.150d3691.svg",
  a + "/_app/immutable/assets/field.8fb526b4.webp",
  a + "/_app/immutable/chunks/stores.44fe59e7.js",
  a + "/_app/immutable/chunks/_docs_v-0.1.3aa69257.js",
  a + "/_app/immutable/chunks/_docs_v-0.1.36c5afe0.js",
  a + "/_app/immutable/chunks/_docs_v-0.1.eb835231.js",
  a + "/_app/immutable/chunks/_docs_v-0.1.cc358e31.js",
  a + "/_app/immutable/chunks/_docs_v-pre-5.837f3a70.js",
  a + "/_app/immutable/chunks/_docs_v-pre-5_en_uwu.254d77d2.js",
  a + "/_app/immutable/chunks/_docs_v-pre-6.c5c9ad42.js",
  a + "/_app/immutable/chunks/_docs_v-pre-6_en_uwu.16f2d150.js",
  a + "/_app/immutable/chunks/_docs_v-rc-1.4f837852.js",
  a + "/_app/immutable/chunks/_docs_v-rc-10.a2c1c3f9.js",
  a + "/_app/immutable/chunks/_docs_v-rc-10_en_uwu.810dc442.js",
  a + "/_app/immutable/chunks/_docs_v-rc-10_ru_ru.a68e3cb7.js",
  a + "/_app/immutable/chunks/_docs_v-rc-11.d6bc8901.js",
  a + "/_app/immutable/chunks/_docs_v-rc-11_en_uwu.c1a6db5c.js",
  a + "/_app/immutable/chunks/_docs_v-rc-11_ru_ru.a68e3cb7.js",
  a + "/_app/immutable/chunks/_docs_v-rc-12.09ce1d9d.js",
  a + "/_app/immutable/chunks/_docs_v-rc-12_en_uwu.428395a0.js",
  a + "/_app/immutable/chunks/_docs_v-rc-13.1acd5718.js",
  a + "/_app/immutable/chunks/_docs_v-rc-13_en_uwu.488e93cc.js",
  a + "/_app/immutable/chunks/_docs_v-rc-14.4fc6b209.js",
  a + "/_app/immutable/chunks/_docs_v-rc-14_en_uwu.342895a7.js",
  a + "/_app/immutable/chunks/_docs_v-rc-1_en_uwu.3f8427b8.js",
  a + "/_app/immutable/chunks/_docs_v-rc-1_ru_ru.a68e3cb7.js",
  a + "/_app/immutable/chunks/_docs_v-rc-2.f8549205.js",
  a + "/_app/immutable/chunks/_docs_v-rc-2_en_uwu.22a1f060.js",
  a + "/_app/immutable/chunks/_docs_v-rc-2_ru_ru.a68e3cb7.js",
  a + "/_app/immutable/chunks/_docs_v-rc-3.0a246ef3.js",
  a + "/_app/immutable/chunks/_docs_v-rc-3_en_uwu.d283fe95.js",
  a + "/_app/immutable/chunks/_docs_v-rc-3_ru_ru.a68e3cb7.js",
  a + "/_app/immutable/chunks/_docs_v-rc-4.49eb4a12.js",
  a + "/_app/immutable/chunks/_docs_v-rc-4_en_uwu.cbf3234c.js",
  a + "/_app/immutable/chunks/_docs_v-rc-4_ru_ru.a68e3cb7.js",
  a + "/_app/immutable/chunks/_docs_v-rc-5.c1f22dcc.js",
  a + "/_app/immutable/chunks/_docs_v-rc-5_en_uwu.7983e190.js",
  a + "/_app/immutable/chunks/_docs_v-rc-5_ru_ru.a68e3cb7.js",
  a + "/_app/immutable/chunks/_docs_v-rc-6.dcb45574.js",
  a + "/_app/immutable/chunks/_docs_v-rc-6_en_uwu.3fae3870.js",
  a + "/_app/immutable/chunks/_docs_v-rc-6_ru_ru.a68e3cb7.js",
  a + "/_app/immutable/chunks/_docs_v-rc-7.dab8bfbc.js",
  a + "/_app/immutable/chunks/_docs_v-rc-7_en_uwu.532e4151.js",
  a + "/_app/immutable/chunks/_docs_v-rc-7_ru_ru.a68e3cb7.js",
  a + "/_app/immutable/chunks/_docs_v-rc-8.4242b87e.js",
  a + "/_app/immutable/chunks/_docs_v-rc-8_en_uwu.5fed128f.js",
  a + "/_app/immutable/chunks/_docs_v-rc-8_ru_ru.a68e3cb7.js",
  a + "/_app/immutable/chunks/_docs_v-rc-9.d98cf3cd.js",
  a + "/_app/immutable/chunks/_docs_v-rc-9_en_uwu.ca8acb93.js",
  a + "/_app/immutable/chunks/_docs_v-rc-9_ru_ru.a68e3cb7.js",
  a + "/_app/immutable/entry/start.cd1afc46.js",
  a + "/_app/immutable/entry/error.svelte.1cf069c2.js",
  a + "/_app/immutable/chunks/gravity.ca0d1868.js",
  a + "/_app/immutable/chunks/pt_pt.cfc632b1.js",
  a + "/_app/immutable/assets/dirt.fb045025.png",
  a + "/_app/immutable/assets/grass_block.dedaa017.png",
  a + "/_app/immutable/assets/sign.c804ceb9.png",
  a + "/_app/immutable/assets/stone.0096954e.png",
  a + "/_app/immutable/assets/sun.d66e4fcc.png",
  a + "/_app/immutable/assets/cheese.9bdf176f.png",
  a + "/_app/immutable/assets/eh.6b23cd84.png",
  a + "/_app/immutable/assets/ok.56d3dd37.png",
  a + "/_app/immutable/assets/_layout.e69fdddb.css",
  a + "/_app/immutable/entry/_layout.svelte.0ab1f540.js",
  a + "/_app/immutable/entry/_layout.ts.d8cd4551.js",
  a + "/_app/immutable/assets/_page.b186cf5c.css",
  a + "/_app/immutable/entry/_page.svelte.1f87e2eb.js",
  a + "/_app/immutable/entry/_version_-layout.svelte.1289dffd.js",
  a + "/_app/immutable/entry/_version_-layout.ts.5b47d716.js",
  a + "/_app/immutable/entry/_version_-page.svelte.b72466e0.js",
  a + "/_app/immutable/entry/_version_-page.ts.1fa92697.js",
  a + "/_app/immutable/entry/_version_-_location_-page.svelte.01043eab.js",
  a + "/_app/immutable/entry/_version_-_location_-page.ts.e1eda850.js",
  a + "/_app/immutable/assets/_page.7408eda2.css",
  a + "/_app/immutable/entry/_version_-all-page.svelte.8a9e7221.js",
  a + "/_app/immutable/entry/_version_-all-page.ts.3eac1f9a.js",
  a + "/_app/immutable/entry/_version_-fav-page.svelte.80cfaac3.js",
  a + "/_app/immutable/entry/_version_-search-page.svelte.e8ac6e5d.js",
  a + "/_app/immutable/entry/_version_-search-page.ts.b5f93f46.js",
  a + "/_app/immutable/assets/_layout.88f12fff.css",
  a + "/_app/immutable/entry/etc-layout.svelte.9f036296.js",
  a + "/_app/immutable/entry/etc-layout.ts.ef9dea09.js",
  a + "/_app/immutable/assets/_page.32459e00.css",
  a + "/_app/immutable/entry/etc-what_are_pings-page.svx.8b6b721a.js"
], m = [
  a + "/favicon.png",
  a + "/manifest.json"
], l = "1689095589700", _ = self, t = `A;static-cache-${l}`, c = u.concat(m);
console.log(c);
_.addEventListener("install", (s) => {
  console.log("[ServiceWorker] Install"), s.waitUntil(
    caches.open(t).then((e) => (console.log("[ServiceWorker] Pre-caching offline page"), e.addAll(c).then(() => {
      _.skipWaiting();
    })))
  );
});
_.addEventListener("activate", (s) => {
  console.log("[ServiceWorker] Activate"), console.log(s), s.waitUntil(
    caches.keys().then(
      async (e) => Promise.all(
        e.map((p) => {
          if (p !== t)
            return console.log("[ServiceWorker] Removing old cache", p), caches.delete(p);
        })
      )
    )
  ), _.clients.claim();
});
self.addEventListener("fetch", (s) => {
  console.log("[ServiceWorker] Fetch", s.request.url), s.respondWith(
    fetch(s.request).catch(() => caches.open(t).then((e) => (console.log(s.request), e.match(s.request.url))))
  );
});
